#!/usr/bin/env python

Import("env")

env_gdfastnoise2 = env.Clone()

# FastNoise source files
fastnoise2_dir = "./FastNoise2/include/"
env_gdfastnoise2.Prepend(CPPPATH=[fastnoise2_dir])

# GD Source files
gdfastnoise2_obj = []

env_gdfastnoise2.add_source_files(gdfastnoise2_obj, "*.cpp")
env.modules_sources += gdfastnoise2_obj

env_gdfastnoise2.Append(LIBPATH=["./FastNoise2/build/src/Release/"])
env_gdfastnoise2.Append(LIBS=['FastNoise'])
env_gdfastnoise2["LIBSUFFIXES"] = ""
